version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto_broker
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  influxdb:
    image: influxdb:2.7
    container_name: influxdb_tsdb
    ports:
      - "127.0.0.1:8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=ems-data

  data-ingestion-service:
    build: ./data-ingestion-service
    container_name: backend_service
    ports:
      - "3001:3001"
    depends_on:
      - mosquitto
      - influxdb
    restart: on-failure

  device-simulator:
    build: ./device-simulator
    container_name: device_simulator
    depends_on:
      - mosquitto
    restart: on-failure

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data: