# 我们移除了过时的 'version' 标签，以消除警告

services:
  mosquitto:
    build: ./mosquitto
    container_name: mosquitto_broker
    networks:
      - ems-net
    ports:
      - "127.0.0.1:1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  influxdb:
    image: influxdb:2.7
    container_name: influxdb_tsdb
    networks:
      - ems-net
    ports:
      - "127.0.0.1:8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=ems-data

  data-ingestion-service:
    build: ./data-ingestion-service
    container_name: backend_service
    networks:
      - ems-net
    ports:
      - "3001:3001"
    depends_on:
      - mosquitto
      - influxdb
    restart: on-failure

  device-simulator:
    build: ./device-simulator
    container_name: device_simulator
    networks:
      - ems-net
    depends_on:
      - mosquitto
    restart: on-failure

# 这里是之前缺失的关键部分：定义我们名叫 ems-net 的网络
networks:
  ems-net:
    driver: bridge

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data: